### ISSUE TITLE
Which languages?

### ISSUE THREAD

**Issue by thrahistan** [braver/method-separator#1]
This only works for javascript or where "function" is written out?
my cpp looks all weird with stripes everywhere

![image](https://cloud.githubusercontent.com/assets/1630552/5703012/e92fcad6-9a60-11e4-83d5-760beafdac40.png)

Could you make it compatible with other languages? :D

**Comment by braver** [comment]
It simply styles all `.meta.function` blocks. Can you share your code? I'll check what's going on.

**Comment by thrahistan** [comment]
I can't share the cpp files contents 

but it should just show up with this code:
![image](https://cloud.githubusercontent.com/assets/1630552/5703772/0acc23d8-9a6b-11e4-9a9e-a4dd411b48d3.png)
just add that to a .cpp file
the mode is UTF-8 C++

or wich code did you mean?

Edit:
![image](https://cloud.githubusercontent.com/assets/1630552/5703830/b4410140-9a6b-11e4-8387-978a42b874c8.png)

Edit2:
.entity.name.function would go but there the lines are before the function name not after the parenthesis
![image](https://cloud.githubusercontent.com/assets/1630552/5704857/5252c482-9a75-11e4-99e0-b89414f0ccaa.png)

I don't know how this works for other languages but cpp, js and coffee are fine with it.

atom-text-editor .entity.name.function,
atom-text-editor::shadow .entity.name.function {
   &::before {
      content: '';
      position: absolute;
      width: 100%;
      height: 1px;
      left: 0;
      top: 0;
      background: red; // wrap guide seems a good choice
      opacity: .5; // set it off from the guide
   }
}

**Comment by braver** [comment]
Yes, styling `entity.name.function` instead of `.meta.function` seems to fix it for c. Thanks!

**Comment by thrahistan** [comment]
no problem :)
