### ISSUE TITLE
Does not seem to work for Golang

### ISSUE THREAD

**Issue by coreyog** [braver/method-separator#4]
Installed and restarted Atom but don't see any separator lines.

**Comment by braver** [comment]
What's the css selector for a method in golang? You should be able to find out using the developer tools.

**Comment by coreyog** [comment]
If I understand correctly (I'm not familiar with atom dev) It looks like you can use the selector `.line > .source.go > .name.function` or something about that. Here's a screen cap for reference.

![methodcss](https://cloud.githubusercontent.com/assets/2836207/10145742/3283aa2a-65e2-11e5-8385-1fcd00537788.PNG)

**Comment by braver** [comment]
Thanks, I made a change that should solve this.
