### ISSUE TITLE
Not working quite right in 1.1.0

### ISSUE THREAD

**Issue by olslash** [braver/method-separator#5]
Granted i didn't try this in an earlier version, but the changes in 1.1.0 may have messed something up?

<img width="482" alt="screen shot 2015-11-02 at 12 51 55 pm" src="https://cloud.githubusercontent.com/assets/693493/10893984/aa4b0ece-8160-11e5-9afa-acd9efa5e0b4.png">

It seems to be choosing some fairly random places to put the markers, although it's clear that `.entity.name.function` is the correct selector, looking at the dom.

**Comment by braver** [comment]
Hmmmm, that ain't right. Haven't looked at this for a while, but I think it doesn't work with the tiled rendering introduced a while back. Should be easy enough to fix the positioning...
