### ISSUE TITLE
Deprecated selector in `method-separator\styles\method-separator.less`

### ISSUE THREAD

**Issue by okonomiyaki3000** [braver/method-separator#8]
In `method-separator\styles\method-separator.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .meta.function:not(.c)::before,
atom-text-editor::shadow .meta.function:not(.c)::before` => `atom-text-editor .meta.function:not(.c)::before,
atom-text-editor.editor .syntax--meta.syntax--function:not(.c)::before`

* `atom-text-editor .name.function::before,
atom-text-editor::shadow .name.function::before` => `atom-text-editor .name.function::before,
atom-text-editor.editor .syntax--name.syntax--function::before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by filipedanielpires** [comment]
Open your config folder, go to packages/method-separator/styles/method-separator.less and remove where you have:
atom-text-editor,
atom-text-editor::shadow {
  .meta.function:not(.c) {
    .separator-mixin()
  }
  .name.function {
    .separator-mixin()
  }
}

remove: atom-text-editor::shadow

and you should stay like this:

atom-text-editor {
  .meta.function:not(.c) {
    .separator-mixin()
  }
  .name.function {
    .separator-mixin()
  }
}

restart your atom and you should be ok
